# Generated by Django 3.2 on 2021-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addantique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='antiquepics')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('enddate', models.DateField()),
            ],
        ),
    ]
